### ISSUE TITLE
EVAL: Redis as Database

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/PackageLock#135]
Redis offers speed, persistence, speed and much more

what do ou think @Kartoffel096

**Comment by HilkopterBob** [comment]
redis supports hash maps, enabling us to dump a struct with arbitrary fields and types under one key (eg. user id) and retrieving one, some, all fields with said key. Redis also supports "reverse lookups", finding a key to a value in hash maps, eg. getting the user id from an associated email. 
https://redis.io/docs/latest/develop/data-types/hashes/

**Comment by Kartoffel096** [comment]
We are going to use redis as DB - this has been discussed in private conversation

**Comment by HilkopterBob** [comment]
We will use valkey as database, see #136
