### ISSUE TITLE
FEATURE: Add tracing

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/PackageLock#52]
Add tracing to function headers as seperate trace headers, giving out the function name to closely follow program flow for debug. Potentially great for plugins, as the callstack can grow extremely large quickly.

Example:
```go
func initDB(. . .) {
log.TraceCurrentFunc()
}
```

Resulting in smth like:
```py
[TRACE] arrived at func: "initDB" | [FILE] db.go
```

What du you think @Kartoffel096 ?

**Comment by Kartoffel096** [comment]
Sounds like a great feature and would love to see that in our codebase

**Comment by HilkopterBob** [comment]
close with #102
