### ISSUE TITLE
BUG: sending request failed for method 'create': timeout

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/PackageLock#53]
Sometimes, a db connection randomly gets a timeout.

Error:
`sending request failed for method 'create': timeout`

The issue comes from one of our dependencies, [surrealdb.go](https://github.com/surrealdb/surrealdb.go)
This issue is for tracking progress in upstream https://github.com/surrealdb/surrealdb.go/issues/148 , for now we have to wait.

**Comment by HilkopterBob** [comment]
Maybe we should srap the surrealdb plans and use sophisticated tools like GORM and postgres? What do you think @Kartoffel096 ?

**Comment by Kartoffel096** [comment]
> Maybe we should srap the surrealdb plans and use sophisticated tools like GORM and postgres? What do you think @Kartoffel096 ?

We should go back and use postgres.
We also should learn from this and really think through a database migration.

**Comment by HilkopterBob** [comment]
Yeah, i will look into that and publish a test-binary for that shortly.

**Comment by HilkopterBob** [comment]
@Kartoffel096 FYI:
The [Golang SDK](https://github.com/surrealdb/surrealdb.go/releases/tag/v0.3.0) got a new release, fixing this issue.

You can still work on a migration to postgres tho.

**Comment by Kartoffel096** [comment]
> You can still work on a migration to postgres tho.

Gonna look into that
