### ISSUE TITLE
FEAT: Add systemd Service-File

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/PackageLock#67]
PackageLock should have a command to automatically generate a systemd service file.
Propossed synopsis:
`packagelock generate` - `unit file`

requesting input @Kartoffel096

**Comment by Kartoffel096** [comment]
We could make a command for this but this sounds like first time setup stuff so it should happen regardless of commands

**Comment by HilkopterBob** [comment]
This issue will be closed. Discussions may move to #70
