### ISSUE TITLE
FEAT: log errors & panics to journalctl

### ISSUE THREAD

**Issue by HilkopterBob** [HilkopterBob/PackageLock#68]
This issue depends on #59 and #67 
Panics and Errors should get logged into journalctl to integrate *our* debugging workflow into the *default* linux debugging workflow.

What do you think @Kartoffel096 ?

**Comment by Kartoffel096** [comment]
Sounds good, panic and errors won't happen often and not clutter the journalctl

**Comment by HilkopterBob** [comment]
as we have a continuous output to stdout, systemd already puts them into journalctl.
https://stackoverflow.com/a/44115973
